#include "catalyst/hooks.hpp"
#include "catalyst/subcommands/generate.hpp"
#include "yaml-cpp/node/node.h"
#include <expected>
#include <filesystem>
#include <fstream>
#include <string>
#include <sys/wait.h>
#include <unordered_set>
#include <vector>
#include <yaml-cpp/yaml.h>

namespace catalyst::generate {
namespace fs = std::filesystem;

std::expected<std::unordered_set<fs::path>, std::string> build_source_set(std::vector<std::string> source_dirs,
                                                                          const std::vector<std::string> &profiles);
void write_variables(const YAML::Node &profile, std::ofstream &buildfile,
                     const std::vector<std::string> &enabled_features);
void write_rules(std::ofstream &buildfile);
std::vector<std::string> intermediate_targets(std::ofstream &buildfile, const std::unordered_set<fs::path> &source_set);
void final_target(const YAML::Node &profile, const auto &object_files, std::ofstream &buildfile);

std::expected<void, std::string> action(const parse_t &parse_args) {

    auto profile_res = profile_composition(parse_args.profiles);
    if (!profile_res)
        return std::unexpected(profile_res.error());
    YAML::Node profile = profile_res.value();

    if (auto res = hooks::pre_generate(profile); !res) {
        return res;
    }

    fs::path current_dir = fs::current_path();
    std::vector<std::string> relative_source_dirs =
        profile["manifest"]["dirs"]["source"].as<std::vector<std::string>>();
    std::vector<std::string> absolute_source_dirs;
    for (const auto &dir : relative_source_dirs) {
        absolute_source_dirs.push_back((current_dir / dir).string());
    }

    auto source_set_res = build_source_set(absolute_source_dirs, parse_args.profiles);
    if (!source_set_res)
        return std::unexpected(source_set_res.error());

    std::unordered_set<std::filesystem::path> source_set = source_set_res.value();

    fs::path build_dir = profile["manifest"]["dirs"]["build"].as<std::string>();
    fs::path obj_dir = build_dir / "obj";

    fs::create_directories(obj_dir);
    if (!fs::exists(obj_dir) || !fs::is_directory(obj_dir)) {
        return std::unexpected("Failed to create object directory: " + obj_dir.string());
    }

    std::ofstream buildfile{build_dir / "build.ninja"};

    if (!buildfile) {
        return std::unexpected(
            std::format("Failed to open {} for writing", fs::path{build_dir / "build.ninja"}.string()));
    }

    buildfile << "# Ninja build file generated by Catalyst\n\n";

    write_variables(profile, buildfile, parse_args.enabled_features);
    write_rules(buildfile);
    std::vector<std::string> object_files = intermediate_targets(buildfile, source_set);
    final_target(profile, object_files, buildfile);

    std::ofstream profile_comp_file{build_dir / "profile_composition.yaml"};
    if (!profile_comp_file) {
        return std::unexpected("Failed to open profile_composition.yaml for writing in " + build_dir.string());
    }
    profile_comp_file << profile;

    if (auto res = hooks::post_generate(profile); !res) {
        return res;
    }
    return {};
}

std::vector<std::string> intermediate_targets(std::ofstream &buildfile,
                                              const std::unordered_set<std::filesystem::path> &source_set) {
    fs::path current_dir = fs::current_path();
    buildfile << "# Source File Compilation\n";
    std::vector<std::string> object_files;
    for (const auto &src : source_set) {
        fs::path relative_src_path = fs::relative(src, current_dir);
        std::string obj_name = relative_src_path.string();
        std::replace(obj_name.begin(), obj_name.end(), '/', '_');
        std::replace(obj_name.begin(), obj_name.end(), '\\', '_'); // For Windows paths
        obj_name = obj_name.substr(0, obj_name.find_last_of('.')) + ".o";
        object_files.push_back((fs::path{"obj"} / obj_name).string());
        buildfile << "build " << object_files.back() << ": "
                  << ((src.extension() == ".c") ? "c_compile" : "cxx_compile") << " " << src.string() << "\n";
    }
    buildfile << "\n";
    return object_files;
}

void final_target(const YAML::Node &profile, const auto &object_files, std::ofstream &buildfile) {
    // Build edge for the final target
    std::string type = profile["manifest"]["type"].as<std::string>();
    std::string target_prefix;
    std::string target_suffix;
    std::string link_rule;

    if (type == "STATICLIB") {
        link_rule = "static_link";
#if defined(_WIN32)
        target_prefix = "";
        target_suffix = ".lib";
#else
        target_prefix = "lib";
        target_suffix = ".a";
#endif
    } else if (type == "SHAREDLIB") {
        link_rule = "shared_link";
#if defined(_WIN32)
        target_prefix = "";
        target_suffix = ".dll";
#elif defined(__APPLE__)
        target_prefix = "lib";
        target_suffix = ".dylib";
#else // Linux and other Unix-likes
        target_prefix = "lib";
        target_suffix = ".so";
#endif
    } else { // BINARY or default
        link_rule = "binary_link";
#if defined(_WIN32)
        target_suffix = ".exe";
#endif
    }

    std::string target_name = profile["manifest"]["name"].as<std::string>();
    fs::path target_path{target_prefix + target_name + target_suffix};
    buildfile << "# Build edge for the final target\n";
    buildfile << "build " << target_path.string() << ": " << link_rule;
    for (const auto &obj : object_files) {
        buildfile << " " << obj;
    }
    buildfile << "\n\n";

    // Default target
    buildfile << "# Default target to build";
    buildfile << "default " << target_path.string() << "\n";
}
} // namespace catalyst::generate
